//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadPensionFamiliar
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pensionado
    {
        public int id { get; set; }
        public int idCliente { get; set; }
        public System.DateTime fechaInicio { get; set; }
        public System.DateTime fechaFin { get; set; }
    
        public virtual Cliente Cliente { get; set; }
    }
}
